-- Debug Telegram Notifications
-- 1. Create a log table to verify triggers are firing
CREATE TABLE IF NOT EXISTS public.debug_notification_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    source_table TEXT,
    payload JSONB,
    status TEXT,
    error_message TEXT
);

-- 2. Update Blood Trigger to Log
CREATE OR REPLACE FUNCTION notify_blood_telegram()
RETURNS TRIGGER AS $$
DECLARE
  function_url TEXT;
  payload JSONB;
  request_id BIGINT;
BEGIN
  -- Log Start
  INSERT INTO public.debug_notification_logs (source_table, payload, status)
  VALUES ('blood_donors', to_jsonb(NEW), 'started');

  function_url := 'https://ocwlkljrjhgqejetgfgw.supabase.co/functions/v1/send-telegram-notification'; 

  payload := jsonb_build_object(
    'type', 'blood',
    'record', to_jsonb(NEW)
  );

  -- Attempt Send
  PERFORM net.http_post(
    url := function_url,
    headers := '{"Content-Type": "application/json"}'::jsonb,
    body := payload
  );

  -- Log Success
  INSERT INTO public.debug_notification_logs (source_table, status)
  VALUES ('blood_donors', 'sent_request');

  RETURN NEW;
EXCEPTION WHEN OTHERS THEN
  -- Log Error
  INSERT INTO public.debug_notification_logs (source_table, payload, status, error_message)
  VALUES ('blood_donors', to_jsonb(NEW), 'error', SQLERRM);
  
  RAISE WARNING 'Blood notification failed: %', SQLERRM;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 3. Update Order Trigger to Log
CREATE OR REPLACE FUNCTION notify_order_telegram()
RETURNS TRIGGER AS $$
DECLARE
  function_url TEXT;
  payload JSONB;
BEGIN
  INSERT INTO public.debug_notification_logs (source_table, payload, status)
  VALUES ('orders', to_jsonb(NEW), 'started');

  function_url := 'https://ocwlkljrjhgqejetgfgw.supabase.co/functions/v1/send-telegram-notification'; 

  payload := jsonb_build_object(
    'type', 'order',
    'record', to_jsonb(NEW)
  );

  PERFORM net.http_post(
    url := function_url,
    headers := '{"Content-Type": "application/json"}'::jsonb,
    body := payload
  );

  INSERT INTO public.debug_notification_logs (source_table, status)
  VALUES ('orders', 'sent_request');

  RETURN NEW;
EXCEPTION WHEN OTHERS THEN
  INSERT INTO public.debug_notification_logs (source_table, payload, status, error_message)
  VALUES ('orders', to_jsonb(NEW), 'error', SQLERRM);
  
  RAISE WARNING 'Order notification failed: %', SQLERRM;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
