-- Create or Update transport_volunteers table
CREATE TABLE IF NOT EXISTS public.transport_volunteers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    -- Personal Info (Admin Only)
    full_name TEXT NOT NULL,
    phone_number TEXT NOT NULL,
    whatsapp TEXT,
    telegram TEXT,
    
    -- Location (Public)
    wilaya TEXT NOT NULL,
    city TEXT NOT NULL,
    
    -- Details (Admin Only)
    additional_info TEXT,
    
    -- Status
    is_available BOOLEAN DEFAULT true,
    status TEXT DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'deleted'))
);

-- Enable RLS
ALTER TABLE public.transport_volunteers ENABLE ROW LEVEL SECURITY;

-- Policy: Admin has full access
DROP POLICY IF EXISTS "Admin Full Access Transport" ON public.transport_volunteers;
CREATE POLICY "Admin Full Access Transport" 
ON public.transport_volunteers
FOR ALL 
TO authenticated 
USING (auth.email() IN ('admin@waseet.com', 'admin@example.com')) 
WITH CHECK (auth.email() IN ('admin@waseet.com', 'admin@example.com'));

-- Policy: Public can insert (Registration)
DROP POLICY IF EXISTS "Public Insert Transport" ON public.transport_volunteers;
CREATE POLICY "Public Insert Transport" 
ON public.transport_volunteers
FOR INSERT 
TO anon, authenticated
WITH CHECK (true);

-- Policy: Public can read ONLY non-deleted items (but columns are filtered in frontend usually, specific DB column security is complex without views, relying on API/Frontend to not fetch private cols for public)
-- Ideally we use a view, but for now we trust the frontend 'select' or 'RPC'. 
-- Let's stick to standard Select policy for now.
DROP POLICY IF EXISTS "Public Read Transport" ON public.transport_volunteers;
CREATE POLICY "Public Read Transport" 
ON public.transport_volunteers
FOR SELECT 
TO anon, authenticated
USING (status = 'active');

-- Grant permissions
GRANT ALL ON public.transport_volunteers TO anon, authenticated, service_role;
